-- MySQL Script generated by MySQL Workbench
-- Sat Jul 13 12:59:26 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `permission` INT,
  `username` VARCHAR(45) NULL,
  `password` TEXT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `report` (
  `idreport` INT NOT NULL AUTO_INCREMENT,
  `image` TEXT NULL,
  `geral` CHAR NULL,
  `v1` CHAR NULL,
  `v2` CHAR NULL,
  `v3` CHAR NULL,
  `v4` CHAR NULL,
  `v5` CHAR NULL,
  `v6` CHAR NULL,
  `avr` CHAR NULL,
  `avl` CHAR NULL,
  `avf` CHAR NULL,
  `i` CHAR NULL,
  `ii` CHAR NULL,
  `iii` CHAR NULL,
  `iduser` INT NULL,
  `deleted` CHAR NULL,
  `timestamp` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idreport`),
  INDEX `report__user_idx` (`iduser` ASC),
  CONSTRAINT `report__user`
    FOREIGN KEY (`iduser`)
    REFERENCES `user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
